### ISSUE TITLE
Ubuntu 14.04 lack file systems for "How to deploy SF within LXC"

### ISSUE THREAD

**Issue by jsyjr** [redhat-cip/software-factory#2] opened 2015-03-18 14:43 UTC
I am trying to follow the "[How to deploy SF within LXC](http://softwarefactory.enovance.com/docs/deploy.html#how-to-deploy-sf-within-lxc)" instructions.  All goes well until I get to

> $ ./start.sh init

The script ends in an exception:

    swfact@gitserver:~/software-factory/bootstraps/lxc$ ./start.sh init
    + set -e
    ...
    + echo 'Now running edeploy-lxc'
    Now running edeploy-lxc
    + sudo /srv/edeploy-lxc/edeploy-lxc --config /var/lib/lxc-conf/sf-lxc.yaml stop
    Stopping all ...
    Traceback (most recent call last):
      File "/srv/edeploy-lxc/edeploy-lxc", line 296, in <module>
        stop()
      File "/srv/edeploy-lxc/edeploy-lxc", line 118, in stop
        stop_one(host['name'], os.path.join(get_overlay_dir(conf), host['name']))
      File "/srv/edeploy-lxc/edeploy-lxc", line 93, in get_overlay_dir
        fs = get_union_filesystem(conf)
      File "/srv/edeploy-lxc/edeploy-lxc", line 89, in get_union_filesystem
        raise Exception('Unsupported fs: ' + ','.join(requested_fs))
    Exception: Unsupported fs: aufs,overlay
    + exit -1

There seem to be multiple issues in the edeploy-lxc script:
- By default Ubuntu 14.04 (at least workstation) does not install any of the filesystems being sought (aufs, overlay, union_fs)
- I can use apt-get to install an overlay**fs** filesystem but it is not known by the name the script expects (*i.e.* overlay with no suffix)
- The script uses the [wrong approach](http://unix.stackexchange.com/questions/98647/can-i-list-the-filesystems-a-running-kernel-can-support) for enumerating the available filesystems

**Comment by lebauce** [comment] 2015-03-18 17:47
Hi.

'overlayfs' has been renamed to 'overlay' when it was merged in the upstream Linux kernel (the Ubuntu kernel carries an old version of overlayfs, still named 'overlayfs').

Unfortunately, the "ls /lib/modules/$(uname -r)/kernel/fs" does not work as the filesystem may have been built into the kernel and not as a module.

A patch to fix the issue is on the way. As a workaround, you can install aufs and manually load aufs with "modprobe aufs".

Thanks

**Comment by morucci** [comment] 2015-03-18 17:54
Hi, Thx for your report.

Just to complete, according to the documentation http://softwarefactory.enovance.com/_docs/deploy.html%7Chow-to-deploy-sf-within-lxc
In order to install the aufs kernel module use :
```
$ sudo apt-get install linux-image-extra-$(uname -r)
```

For Software Factory we have never tested with overlay FS, and only support the aufs way.

**Comment by morucci** [comment] 2015-10-08 17:57
I'm closing this issue as ubuntu is no longer supported. Please have a look to new 2.0.0 version.

**Closed by morucci** 2015-10-08 17:57 UTC
